# without column transfer

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df= pd.read_csv('covid_toy.csv')

In [4]:
df.sample(5)

    age  gender  fever   cough       city has_covid
77    8  Female  101.0    Mild    Kolkata        No
69   73  Female  103.0    Mild      Delhi        No
15   70    Male  103.0  Strong    Kolkata       Yes
85   16  Female  103.0    Mild  Bangalore       Yes
91   38    Male    NaN    Mild      Delhi       Yes

In [5]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [6]:
X_train

    age  gender  fever   cough       city
17   40  Female   98.0  Strong      Delhi
35   82  Female  102.0  Strong  Bangalore
63   10    Male  100.0    Mild  Bangalore
64   42    Male  104.0    Mild     Mumbai
49   44    Male  104.0    Mild     Mumbai
..  ...     ...    ...     ...        ...
98    5  Female   98.0  Strong     Mumbai
0    60    Male  103.0    Mild    Kolkata
62   56  Female  104.0  Strong  Bangalore
90   59  Female   99.0  Strong      Delhi
76   80    Male  100.0    Mild  Bangalore

[80 rows x 5 columns]

In [7]:
X_test

    age  gender  fever   cough       city
58   23    Male   98.0  Strong     Mumbai
68   54  Female  104.0  Strong    Kolkata
57   49  Female   99.0  Strong  Bangalore
48   66    Male   99.0  Strong  Bangalore
12   25  Female   99.0  Strong    Kolkata
79   48  Female  103.0    Mild    Kolkata
67   65    Male   99.0    Mild  Bangalore
7    20  Female    NaN  Strong     Mumbai
20   12    Male   98.0  Strong  Bangalore
56   71    Male    NaN  Strong    Kolkata
8    19  Female  100.0  Strong  Bangalore
52   47  Female  100.0  Strong  Bangalore
43   22  Female   99.0    Mild  Bangalore
9    64  Female  101.0    Mild      Delhi
83   17  Female  104.0    Mild    Kolkata
33   26  Female   98.0    Mild    Kolkata
44   20    Male  102.0  Strong      Delhi
11   65  Female   98.0    Mild     Mumbai
24   13  Female  100.0  Strong    Kolkata
28   16    Male  104.0    Mild    Kolkata

In [8]:
#adding simple imputer to fever column
si=SimpleImputer()

X_train_fever= si.fit_transform(X_train[['fever']])

X_test_fever= si.fit_transform(X_test[['fever']])

#missing values will be replaced by the mean of data in this

In [9]:
X_train_fever.shape

(80, 1)

In [10]:
#ordinal encoding to cough column

oe=OrdinalEncoder(categories=[['Mild','Strong']])

X_train_cough=oe.fit_transform(X_train[['cough']])

X_test_cough=oe.fit_transform(X_test[['cough']])

In [11]:
X_train_cough

array([[1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.]])

In [12]:
#one hot encoding on gender and cities 

ohe=OneHotEncoder(drop='first',sparse=False)

X_train_gender_city=ohe.fit_transform(X_train[['gender','city']])

X_test_gender_city=ohe.fit_transform(X_test[['gender','city']])

/Users/nikhil/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/Users/nikhil/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [13]:
X_train_gender_city

array([[0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

In [14]:
#extracting age 

X_train_age= X_train.drop(columns=['gender','fever','cough','city']).values

X_test_age=X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [15]:
X_train_transformed=np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)

In [16]:
X_test_transformed=np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

In [17]:
X_train_transformed

array([[ 40.        ,  98.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 82.        , 102.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 10.        , 100.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 42.        , 104.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 44.        , 104.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 82.        , 102.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 34.        , 101.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 72.        ,  99.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 34.        , 100.98611111,   0.        ,   0.        ,
          0.        ,   1.        ,   1.        ],
       [ 65.        , 101.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 33.        , 102.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 51.        , 104.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 42.        , 100.98611111,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 84.        , 100.98611111,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 19.        , 101.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 11.        , 100.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 24.        , 102.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 27.        , 100.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 19.        , 101.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 51.        , 101.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [  5.        , 100.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 10.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 71.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 50.        , 103.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 18.        , 104.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 34.        ,  98.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 75.        , 104.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 24.        ,  98.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 15.        , 101.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 25.        , 104.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 20.        , 101.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 82.        , 100.98611111,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 27.        , 100.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 19.        , 100.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 65.        ,  99.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 83.        , 103.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 27.        , 100.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 60.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 38.        , 101.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 68.        , 101.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 83.        , 101.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 81.        , 101.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 23.        , 100.98611111,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 70.        , 103.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 73.        ,  98.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 81.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   1.        ],
       [ 83.        ,  98.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 14.        , 101.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [  8.        , 101.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 49.        , 102.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [  5.        , 102.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 64.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 74.        , 102.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 69.        , 103.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 64.        , 102.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 79.        , 100.98611111,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 51.        , 104.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 46.        , 103.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 69.        , 102.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 55.        , 100.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 34.        , 104.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 42.        , 101.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 11.        , 100.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 12.        , 104.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 73.        , 103.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 69.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   1.        ],
       [  6.        , 104.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 75.        , 100.98611111,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 31.        ,  98.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 38.        , 100.98611111,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 47.        , 101.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 16.        , 103.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 80.        ,  98.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 49.        , 101.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 14.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [  5.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   1.        ],
       [ 60.        , 103.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 56.        , 104.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 59.        ,  99.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 80.        , 100.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ]])

In [18]:
X_train_transformed.shape

(80, 7)

# with column transformer

In [19]:
from sklearn.compose import ColumnTransformer

In [20]:
#(transformer_name(any),type,columns)

transformer=ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse=False,drop='first'),['gender','city'])
],remainder='passthrough') #there are two opt for remainder drop or pass through deop or passthrough

In [23]:
X_train_trans=transformer.fit_transform(X_train)

/Users/nikhil/anaconda3/lib/python3.11/site-packages/sklearn/preprocessing/_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [24]:
X_train_trans.shape

(80, 7)

In [25]:
transformer.transform(X_test).shape

(20, 7)